/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    FilterBox: typeof import('./src/components/FilterBox.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    LessonCard: typeof import('./src/components/LessonCard.vue')['default']
    MultiSelect: typeof import('./src/components/MultiSelect.vue')['default']
    NoClassesFound: typeof import('./src/components/NoClassesFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudioIcon: typeof import('./src/components/StudioIcon.vue')['default']
  }
}
