import requests
import json
from movement.movement import movement
from imi.imi import imi
from xo.xo import xo
from ix.ix import ix
from pdc.pdc import pdc
import datetime


# Globals
location = './sydney-dance-classes/data/'

# Note that currently for authorisation, the token is hardcoded and will expire after a certain time
# Get new token from accessing webpage if it doesnt work
#mnh_auth = "1wJDsV3ZG9ljZuHHRoy0y1UCtr-yL89st8SuzeTw4AA.eyJpbnN0YW5jZUlkIjoiZjI4MWM2ZjItOGMxMy00ZDRmLTlmYWMtYjgwYTE1NTZlZmIxIiwiYXBwRGVmSWQiOiIxM2QyMWM2My1iNWVjLTU5MTItODM5Ny1jM2E1ZGRiMjdhOTciLCJtZXRhU2l0ZUlkIjoiMzQyMGE5MjktMzUwYy00NGFkLWE1M2ItMmM0NTQ1NzMyNjM2Iiwic2lnbkRhdGUiOiIyMDI0LTA5LTE3VDE5OjE4OjI3LjM4M1oiLCJ2ZW5kb3JQcm9kdWN0SWQiOiJib29raW5ncyIsImRlbW9Nb2RlIjpmYWxzZSwiYWlkIjoiY2ViZTE3MjEtODdhNC00NTc5LWFjNzMtMWEzMmI5Y2RhMGFjIiwiYmlUb2tlbiI6ImM2YTE2ZmRiLWI5MWYtMDllMi0zYTk3LTk0NGY1MDI1Yzk4NyIsInNpdGVPd25lcklkIjoiZTQ1NDYxYzMtNjRhZC00ZDlmLTg0NGUtNzc0MGJjMjU2NGE2In0"
#mnp_auth = "aOhvictdeaKTuQxsdRXNiy5tz_uchUKgsodI7ygk9Cc.eyJpbnN0YW5jZUlkIjoiYWJjNTcxYzItMzhlMC00ZGMzLWI4MGEtZmJkZTRhNTk4YzcyIiwiYXBwRGVmSWQiOiIxM2QyMWM2My1iNWVjLTU5MTItODM5Ny1jM2E1ZGRiMjdhOTciLCJtZXRhU2l0ZUlkIjoiZDFkZjNhMTUtNWYwZC00OWZjLWJkNmYtNDc0NmI4OGZjNTRjIiwic2lnbkRhdGUiOiIyMDI0LTA2LTI0VDA0OjA1OjQwLjk0NloiLCJ2ZW5kb3JQcm9kdWN0SWQiOiJib29raW5ncyIsImRlbW9Nb2RlIjpmYWxzZSwib3JpZ2luSW5zdGFuY2VJZCI6ImYyODFjNmYyLThjMTMtNGQ0Zi05ZmFjLWI4MGExNTU2ZWZiMSIsImFpZCI6ImEzOWQ0NmU1LTQxNzAtNDdlNC1hZDViLTcwNzc1ODQxMzJlOSIsImJpVG9rZW4iOiI3YTFhNGJkNy02N2VkLTA0M2YtMDU2NS1iYzk4ZjJkNjQ5M2UiLCJzaXRlT3duZXJJZCI6ImU0NTQ2MWMzLTY0YWQtNGQ5Zi04NDRlLTc3NDBiYzI1NjRhNiJ9"

imi_callback = "jQuery36406886794353924179_1715325689640"
imi__id = "1715325689641"

today = datetime.date.today()
today_weekday = today.weekday()
previous_monday = today - datetime.timedelta(days=today_weekday)
upcoming_sunday = today + datetime.timedelta(days=(7 + 6 - today_weekday))

# movement(location, previous_monday, upcoming_sunday)
# imi(imi_callback, today, imi__id, location)
# xo(location)
# ix(location, previous_monday, upcoming_sunday)
pdc(location, previous_monday, upcoming_sunday)
print("Scraping completed")