import requests
import json
from movement.movement import movement
import datetime

# Note that currently for authorisation, the token is hardcoded and will expire after a certain time
# Get new token from accessing webpage if it doesnt work
mnh_auth = "6Smub3RuBJwNtNwjySqEepcqBzZpIgOke4wIQbXouBA.eyJpbnN0YW5jZUlkIjoiZjI4MWM2ZjItOGMxMy00ZDRmLTlmYWMtYjgwYTE1NTZlZmIxIiwiYXBwRGVmSWQiOiIxM2QyMWM2My1iNWVjLTU5MTItODM5Ny1jM2E1ZGRiMjdhOTciLCJtZXRhU2l0ZUlkIjoiMzQyMGE5MjktMzUwYy00NGFkLWE1M2ItMmM0NTQ1NzMyNjM2Iiwic2lnbkRhdGUiOiIyMDI0LTA1LTAyVDEwOjE2OjQ3Ljk3NVoiLCJ2ZW5kb3JQcm9kdWN0SWQiOiJib29raW5ncyIsImRlbW9Nb2RlIjpmYWxzZSwiYWlkIjoiZGMzNmZmZDktMDFhYy00MGJjLWJiOTMtMGYzOTJiMjU4YzMzIiwiYmlUb2tlbiI6ImM2YTE2ZmRiLWI5MWYtMDllMi0zYTk3LTk0NGY1MDI1Yzk4NyIsInNpdGVPd25lcklkIjoiZTQ1NDYxYzMtNjRhZC00ZDlmLTg0NGUtNzc0MGJjMjU2NGE2In0"
mnp_auth = "B_dksoiWxcUXDiQ3XcmtiE7igZ8s6IRWsjP5gRBXiG4.eyJpbnN0YW5jZUlkIjoiYWJjNTcxYzItMzhlMC00ZGMzLWI4MGEtZmJkZTRhNTk4YzcyIiwiYXBwRGVmSWQiOiIxM2QyMWM2My1iNWVjLTU5MTItODM5Ny1jM2E1ZGRiMjdhOTciLCJtZXRhU2l0ZUlkIjoiZDFkZjNhMTUtNWYwZC00OWZjLWJkNmYtNDc0NmI4OGZjNTRjIiwic2lnbkRhdGUiOiIyMDI0LTA1LTAyVDEwOjQxOjI5LjI2NFoiLCJ2ZW5kb3JQcm9kdWN0SWQiOiJib29raW5ncyIsImRlbW9Nb2RlIjpmYWxzZSwib3JpZ2luSW5zdGFuY2VJZCI6ImYyODFjNmYyLThjMTMtNGQ0Zi05ZmFjLWI4MGExNTU2ZWZiMSIsImFpZCI6ImEzOWQ0NmU1LTQxNzAtNDdlNC1hZDViLTcwNzc1ODQxMzJlOSIsImJpVG9rZW4iOiI3YTFhNGJkNy02N2VkLTA0M2YtMDU2NS1iYzk4ZjJkNjQ5M2UiLCJzaXRlT3duZXJJZCI6ImU0NTQ2MWMzLTY0YWQtNGQ5Zi04NDRlLTc3NDBiYzI1NjRhNiJ9"

today = datetime.date.today()
today_weekday = today.weekday()
previous_monday = today - datetime.timedelta(days=today_weekday)
upcoming_sunday = today + datetime.timedelta(days=(6 - today_weekday))

movement(mnh_auth, mnp_auth, '../sydney-dance-classes/data/', previous_monday, upcoming_sunday)
